kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dedicated-admin-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - monitoring.coreos.com
- apiGroups:
  - rbac.authorization.k8s.io
  attributeRestrictions: null
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"