kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dedicated-admin-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
- apiGroups:
  - rbac.authorization.k8s.io
  attributeRestrictions: null
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - "*"
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - limitranges
  - resourcequotas
  verbs:
  - "*"