apiVersion: apps/v1
kind: Deployment
metadata:
  name: dedicated-admin-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: dedicated-admin-operator
  template:
    metadata:
      labels:
        k8s-app: dedicated-admin-operator
    spec:
      serviceAccountName: dedicated-admin-operator
      containers:
        - name: dedicated-admin-operator
        # TODO - rename image when we have an official SRE Org on quay.io
          image: quay.io/rogbas/dedicated-admin-operator:latest
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - dedicated-admin-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "dedicated-admin-operator"
