apiVersion: authorization.openshift.io/v1
groupNames:
- dedicated-admins
- system:serviceaccounts:dedicated-admin
kind: ClusterRoleBinding
metadata:
  name: dedicated-cluster-admin
roleRef:
  name: dedicated-cluster-admin
subjects:
- kind: Group
  name: dedicated-admins
- kind: SystemGroup
  name: system:serviceaccounts:dedicated-admin
