---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dedicated-admin-operator
  namespace: openshift-dedicated-admin
rules:
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
