apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dedicated-admin-operator
subjects:
- kind: ServiceAccount
  name: dedicated-admin-operator
  namespace: openshift-dedicated-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dedicated-admin-operator
---
# operator can create rolebindings to admin clusterrole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dedicated-admin-operator-admin
subjects:
- kind: ServiceAccount
  name: dedicated-admin-operator
  namespace: openshift-dedicated-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
# operator can create rolebindings to dedicated-admins-project clusterrole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dedicated-admin-operator-project
subjects:
- kind: ServiceAccount
  name: dedicated-admin-operator
  namespace: openshift-dedicated-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dedicated-admins-project
