apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dedicated-admin-operator
  namespace: openshift-dedicated-admin
subjects:
- kind: ServiceAccount
  name: dedicated-admin-operator
  namespace: openshift-dedicated-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dedicated-admin-operator
