kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dedicated-admin-operator
subjects:
- kind: ServiceAccount
  name: dedicated-admin-operator
  namespace: openshift-dedicated-admin
roleRef:
  kind: ClusterRole
  name: dedicated-admin-operator
  apiGroup: rbac.authorization.k8s.io
