kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dedicated-admin-operator
subjects:
- kind: ServiceAccount
  name: dedicated-admin-operator
  namespace: openshift-dedicated-admin
roleRef:
  kind: ClusterRole
  name: dedicated-admin-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dedicated-admin-operator-configmaps
  namespace: openshift-dedicated-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dedicated-admin-operator-configmaps
subjects:
- kind: ServiceAccount
  name: dedicated-admin-operator
  namespace: openshift-dedicated-admin

