apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dedicated-admins-openshift-operators
  namespace: openshift-operators
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  - clusterserviceversions
  verbs:
  - "*"
