apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: dedicated-admin-operator
  namespace: openshift-dedicated-admin
spec:
  channel: ${CHANNEL}
  name: dedicated-admin-operator
  source: dedicated-admin-operator-registry
  sourceNamespace: openshift-dedicated-admin
