kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-scrap
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
roleRef:
  kind: Role
  name: prometheus-k8s
  namespace: openshift-monitoring
  apiGroup: rbac.authorization.k8s.io
